# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/dory/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/dory/proprietary/bin/batteryd:system/bin/batteryd \
    vendor/lge/dory/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/lge/dory/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/lge/dory/proprietary/lib/hw/lis3dsh_tilt.so:system/lib/hw/lis3dsh_tilt.so \
    vendor/lge/dory/proprietary/lib/hw/sensors.msm8226.so:system/lib/hw/sensors.msm8226.so \
    vendor/lge/dory/proprietary/lib/hw/sensors.invensense.so:system/lib/hw/sensors.invensense.so \
    vendor/lge/dory/proprietary/vendor/firmware/BCM20702A.hcd:system/vendor/firmware/BCM20702A.hcd \
    vendor/lge/dory/proprietary/vendor/firmware/a330_pfp.fw:system/vendor/firmware/a330_pfp.fw \
    vendor/lge/dory/proprietary/vendor/firmware/a330_pm4.fw:system/vendor/firmware/a330_pm4.fw \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b00:system/vendor/firmware/adsp.b00 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b01:system/vendor/firmware/adsp.b01 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b02:system/vendor/firmware/adsp.b02 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b03:system/vendor/firmware/adsp.b03 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b04:system/vendor/firmware/adsp.b04 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b05:system/vendor/firmware/adsp.b05 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b06:system/vendor/firmware/adsp.b06 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b07:system/vendor/firmware/adsp.b07 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b08:system/vendor/firmware/adsp.b08 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b09:system/vendor/firmware/adsp.b09 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b10:system/vendor/firmware/adsp.b10 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b11:system/vendor/firmware/adsp.b11 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.b12:system/vendor/firmware/adsp.b12 \
    vendor/lge/dory/proprietary/vendor/firmware/adsp.mdt:system/vendor/firmware/adsp.mdt \
    vendor/lge/dory/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/lge/dory/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/lge/dory/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/lge/dory/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/lge/dory/proprietary/vendor/lib/egl/libplayback_adreno.so:system/vendor/lib/egl/libplayback_adreno.so \
    vendor/lge/dory/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/lge/dory/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/lge/dory/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/lge/dory/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/lge/dory/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/lge/dory/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/lge/dory/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/lge/dory/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/lge/dory/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/lge/dory/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    vendor/lge/dory/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/lge/dory/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/lge/dory/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/lge/dory/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so
